In [1]:
import torch

In [2]:
#construct a tensor
x = torch.tensor([1., 2.])

print(x)

tensor([1., 2.])


In [3]:
#product of 2 tensors

x = torch.tensor([1., 2.])
y = torch.tensor([3., 4.])

print(x * y)

tensor([3., 8.])


In [5]:
# returning elements of a tensor

x = torch.tensor([[1., 2.],[5., 3.],[0., 4.]])

print(x)

print(x[0][1])

print(x[0][1].item())

tensor([[1., 2.],
        [5., 3.],
        [0., 4.]])
tensor(2.)
2.0


In [6]:
print(x.shape)

torch.Size([3, 2])
